server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hongzhi?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5
#logging:
#  level:
#    SpringbootMaven: DEBUG 
#优先级从高到低依次为：OFF FATAL ERROR WARN INFO DEBUG TRACE ALL
#ALL   最低等级的用于打开所有日志记录
#TRACE 很低的日志级别一般不会使用
#DEBUG 指出细粒度信息事件对调试应用程序是非常有帮助的 主要用于开发过程中打印一些重要信息
#INFO  消息在粗粒度级别上突出强调应用程序的运行过程
#      打印一些你感兴趣的或者重要的信息， 这个可以用于生产环境中输出程序运行的一些重要信息
#      但是不能滥用避免打印过多的日志
#WARN  表明会出现潜在错误的情形有些信息不是错误信息但是也要给程序员的一些提示
#ERROR 指出虽然发生错误事件 但仍然不影响系统的继续运行
#      打印错误和异常信息如果不想输出太多的日志可以使用这个级别
#FATAL 指出每个严重的错误事件将会导致应用程序的退出
#      这个级别比较高了重大错误 这种级别你可以直接停止程序了
#OFF   最高等级的，用于关闭所有日志记录


#server:
#  port: 80
#  servlet:#    context-path: /deviceinfo/doLogin